forge 'https://forge.puppet.com'

# Modules discovered by generate-puppetfile
mod 'puppetlabs/apache',    '5.1.0'
mod 'puppetlabs/concat',    '6.1.0'
mod 'puppetlabs/stdlib',    '6.1.0'
mod 'puppetlabs/translate', '2.0.0'
mod 'puppetlabs/tomcat',    '3.1.0'
mod 'puppet/archive',       '4.3.0'
